# syntax=dhi.io/build:2-helm3

name: Crossplane Helm chart 2.x
image: dhi.io/crossplane-chart
variant: helm
tags:
  - 2.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b7aa9852801ca9959eefdad8233f95635df348c2
  CROSSPLANE_REFERENCE: dhi/crossplane:2.2.0-debian13@sha256:b1bef54a471697f7392d733df30db53d9d1ae4db9b62de1113c354a03aafb89f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  SEMVER_MAJOR_MINOR_VERSION: "2.2"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.2.0
  VERSION: 2.2.0
contents:
  builds:
    - name: crossplane
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        files:
          - url: git+https://github.com/crossplane/crossplane.git#v2.2.0
            checksum: b7aa9852801ca9959eefdad8233f95635df348c2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/cluster/charts/crossplane
          with:
            chart:
              appRef: crossplane
              description: Docker Hardened Images Helm chart for Crossplane
              images:
                - name: crossplane
                  ref: dhi/crossplane:2.2.0-debian13@sha256:b1bef54a471697f7392d733df30db53d9d1ae4db9b62de1113c354a03aafb89f
              name: crossplane-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/crossplane/crossplane
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/cluster/charts/crossplane
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/cluster/charts/crossplane
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/cluster/charts
          with:
            chart: crossplane
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/cluster/charts/crossplane
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/crossplane/config
