# syntax=dhi.io/build:2-alpine3.23

name: Prometheus Config Reloader 0.x (dev)
image: dhi.io/prometheus-config-reloader
variant: dev
tags:
  - 0-alpine3.23-dev
  - 0.90-alpine3.23-dev
  - 0.90.0-alpine3.23-dev
platforms:
  - linux/amd64
  - linux/arm64
vars:
  FLAVORED_SUFFIX: -dev
  SEMVER_MAJOR_MINOR_VERSION: "0.90"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.90.0
  SUFFIX: -dev
  VERSION: 0.90.0-r0
contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
  packages:
    - alpine-baselayout-data
    - apk-tools
    - busybox
    - ca-certificates
    - ca-certificates-bundle
    - prometheus-config-reloader-dev
    - tzdata
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.23"
  pretty-name: Docker Hardened Images/Alpine Linux v3.23
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
paths:
  - type: directory
    path: /bin
    uid: 0
    gid: 0
    mode: "0755"
  - type: symlink
    path: /bin/prometheus-config-reloader
    uid: 0
    gid: 0
    source: /usr/bin/prometheus-config-reloader
annotations:
  org.opencontainers.image.description: A minimal prometheus-config-reloader image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - prometheus-config-reloader
