metadata:
  display-name: Envoy Gateway Helm chart
  short-description: Envoy Gateway helm chart is an open source project for managing Envoy Proxy as a Kubernetes-based application gateway.
  featured: false
  home-url: https://github.com/envoyproxy/gateway/tree/main/charts/gateway-helm
  categories:
    - networking
