metadata:
  display-name: APISIX Helm chart
  short-description: Apache APISIX is a dynamic, real-time, high-performance API Gateway.
  featured: false
  home-url: https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix
  categories:
    - api-management
    - monitoring-and-observability
    - security
