# syntax=dhi.io/build:2-helm3

name: Velero Helm chart 11.x
image: dhi.io/velero-chart
variant: helm
tags:
  - 11.3.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b07a5226f3e4b25b8d44ea2266dac680bf8b5c2a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  KUBECTL_REFERENCE: dhi/kubectl:1.35.3-debian13-compat@sha256:67b2be6b120b98e04c9f48c992aa3cc9ca29d2c6d48aa8cdf6f2e70779fb912e
  SEMVER_MAJOR_MINOR_VERSION: "11.3"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.3.2
  VELERO_REFERENCE: dhi/velero:1.18.0-debian13@sha256:1047f3ca4b6f97610968fb8c8b5ee623021a147269c5bd7c2e8f3e1cd1411c01
  VERSION: 11.3.2
contents:
  builds:
    - name: velero
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        files:
          - url: git+https://github.com/vmware-tanzu/helm-charts.git#velero-11.3.2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            chart:
              appRef: velero
              description: Docker Hardened Images Helm chart for Velero
              images:
                - name: velero
                  ref: dhi/velero:1.18.0-debian13@sha256:1047f3ca4b6f97610968fb8c8b5ee623021a147269c5bd7c2e8f3e1cd1411c01
                - name: kubectl
                  ref: dhi/kubectl:1.35.3-debian13-compat@sha256:67b2be6b120b98e04c9f48c992aa3cc9ca29d2c6d48aa8cdf6f2e70779fb912e
              name: velero-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vmware-tanzu/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            process-templates: true
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: velero
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/velero/config
