# syntax=dhi.io/build:2-helm3

name: Strimzi Kafka Operator Helm chart 0.x
image: dhi.io/strimzi-kafka-operator-chart
variant: helm
tags:
  - 0.1.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 54081abf97d0e5e524de773b88343756934db1a8
  CHART_VERSION: 0.1.1
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  SEMVER_MAJOR_MINOR_VERSION: "0.51"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.51.0
  STRIMZI_KAFKA_REFERENCE: dhi/strimzi-kafka:0.50.1-debian13-kafka-4.1.1@sha256:e5d4c733b17ffb0c9332d723ce1f257915045330ca7a77184972d85ac356cac0
  STRIMZI_OPERATOR_REFERENCE: dhi/strimzi-operator:0.51.0-debian13@sha256:5011e0b5606baf8e3e9355e1c52623d810e318808f8e0a86ff8b3f7301c051d6
  VERSION: 0.51.0
contents:
  builds:
    - name: strimzi-kafka-operator
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/strimzi/strimzi-kafka-operator.git#0.51.0
            checksum: 54081abf97d0e5e524de773b88343756934db1a8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            chart:
              appRef: strimzi-operator
              description: Docker Hardened Images Helm chart for Strimzi Kafka Operator
              images:
                - name: strimzi-operator
                  ref: dhi/strimzi-operator:0.51.0-debian13@sha256:5011e0b5606baf8e3e9355e1c52623d810e318808f8e0a86ff8b3f7301c051d6
                - name: strimzi-kafka
                  ref: dhi/strimzi-kafka:0.50.1-debian13-kafka-4.1.1@sha256:e5d4c733b17ffb0c9332d723ce1f257915045330ca7a77184972d85ac356cac0
              name: strimzi-kafka-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/strimzi/strimzi-kafka-operator
              version: 0.1.1
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/strimzi-kafka-operator/config
