# syntax=dhi.io/build:2-alpine3.23

name: Alertmanager 0.x (dev)
image: dhi.io/alertmanager
variant: dev
tags:
  - 0-alpine3.23-dev
  - 0.31-alpine3.23-dev
  - 0.31.1-alpine3.23-dev
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: 7a639ba087d6e877038cabfdaa645230f79001b8
  FLAVORED_SUFFIX: -dev
  SEMVER_MAJOR_MINOR_VERSION: "0.31"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.31.1
  SUFFIX: -dev
  VERSION: 0.31.1-r4
contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
  packages:
    - alertmanager-dev
    - alpine-baselayout-data
    - apk-tools
    - busybox
    - ca-certificates
    - ca-certificates-bundle
    - tzdata
  files:
    - url: https://raw.githubusercontent.com/prometheus/alertmanager/7a639ba087d6e877038cabfdaa645230f79001b8/examples/ha/alertmanager.yml
      path: /etc/alertmanager/alertmanager.yml
      uid: 65532
      gid: 65532
      mode: "0644"
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.23"
  pretty-name: Docker Hardened Images/Alpine Linux v3.23
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
paths:
  - type: directory
    path: /alertmanager
    uid: 65532
    gid: 65532
    mode: "0755"
annotations:
  org.opencontainers.image.description: A minimal Alertmanager image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - alertmanager
cmd:
  - --config.file=/etc/alertmanager/alertmanager.yml
  - --storage.path=/alertmanager
