# syntax=dhi.io/build:2-helm3

name: Clickhouse Operator Helm chart 0.x
image: dhi.io/clickhouse-operator-chart
variant: helm
tags:
  - 0.26.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 166d8fa963458df55648b57eebd5d20faefb7345
  CLICKHOUSE_METRICS_EXPORTER_REFERENCE: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:aaa9366a81b09146be6476df22c25fcacb86a4ae97b79dcfb3251d23b136812f
  CLICKHOUSE_OPERATOR_IMAGE_TAG: 0.25.5
  CLICKHOUSE_OPERATOR_REFERENCE: dhi/clickhouse-operator:0.25.6-debian13@sha256:a24eef05c8d58ec419d405fc942ee066a30202433656edbbc2756fb631891996
  CLICKHOUSE_SERVER_REFERENCE: dhi/clickhouse-server:25.8.21-debian13@sha256:06de316a2716ecc1a36d8845fafb53e15d58a6cc2d1503ae78c36bcededd97d4
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  KUBECTL_REFERENCE: dhi/kubectl:1.34.6-alpine3.22-dev@sha256:80ddff9743e5e37a4863fedc496fc5d56d6523d2e104634915f9dd28e6cd12f9
  SEMVER_MAJOR_MINOR_VERSION: "0.26"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.26.2
  VERSION: 0.26.2
contents:
  builds:
    - name: clickhouse-operator-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        files:
          - url: git+https://github.com/Altinity/clickhouse-operator.git#release-0.26.2
            checksum: 166d8fa963458df55648b57eebd5d20faefb7345
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            chart:
              appRef: clickhouse-operator
              description: Docker Hardened Images Helm chart for ClickHouse Operator
              images:
                - name: clickhouse-operator
                  ref: dhi/clickhouse-operator:0.25.6-debian13@sha256:a24eef05c8d58ec419d405fc942ee066a30202433656edbbc2756fb631891996
                - name: clickhouse-metrics-exporter
                  ref: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:aaa9366a81b09146be6476df22c25fcacb86a4ae97b79dcfb3251d23b136812f
                - name: clickhouse-server
                  ref: dhi/clickhouse-server:25.8.21-debian13@sha256:06de316a2716ecc1a36d8845fafb53e15d58a6cc2d1503ae78c36bcededd97d4
                - name: kubectl
                  ref: dhi/kubectl:1.34.6-alpine3.22-dev@sha256:80ddff9743e5e37a4863fedc496fc5d56d6523d2e104634915f9dd28e6cd12f9
              name: clickhouse-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/Altinity/clickhouse-operator
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: clickhouse-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/clickhouse-operator/config
