# syntax=dhi.io/build:2-helm3

name: Envoy Gateway Helm chart 1.x
image: dhi.io/envoy-gateway-chart
variant: helm
tags:
  - 1.7.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 3f75d826cc1dbd3d66632abbd45f96388d226c1d
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  ENVOY_GATEWAY_IMAGE_REFERENCE: dhi/envoy-gateway:1.7.1-debian13@sha256:65ce674d97dd8ce35278b5c16f9a5ea31467b2cb4c01d43d931c620752502375
  ENVOY_IMAGE_REFERENCE: dhi/envoy:1.37.1-debian13@sha256:034dc62dc83b95d7817fe19851de847efa1e03f972e71c227e01abb2a2515878
  ENVOY_RATELIMIT_IMAGE_REFERENCE: dhi/envoy-ratelimit:05c08d0394737a24729e01519629420a4d86b865-debian13@sha256:1c4546f8ccc6c08a3424955618c82a2df05be821756f610162ab95a52a920164
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  SEMVER_MAJOR_MINOR_VERSION: "1.7"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.7.1
  VERSION: 1.7.1
contents:
  builds:
    - name: envoy-gateway-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        files:
          - url: git+https://github.com/envoyproxy/gateway.git#v1.7.1
            checksum: 3f75d826cc1dbd3d66632abbd45f96388d226c1d
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/gateway-helm
          with:
            chart:
              appRef: envoy-gateway
              description: Docker Hardened Images Helm chart for Envoy Gateway
              images:
                - name: envoy-gateway
                  ref: dhi/envoy-gateway:1.7.1-debian13@sha256:65ce674d97dd8ce35278b5c16f9a5ea31467b2cb4c01d43d931c620752502375
                - name: envoy-ratelimit
                  ref: dhi/envoy-ratelimit:05c08d0394737a24729e01519629420a4d86b865-debian13@sha256:1c4546f8ccc6c08a3424955618c82a2df05be821756f610162ab95a52a920164
                - name: envoy
                  ref: dhi/envoy:1.37.1-debian13@sha256:034dc62dc83b95d7817fe19851de847efa1e03f972e71c227e01abb2a2515878
              name: envoy-gateway-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/envoyproxy/gateway
            cmd: prepare
            registry: dhi.io
        - name: rename values file
          work-dir: ${source.dir}/helm-charts/charts/gateway-helm
          runs: |
            set -eux -o pipefail

            mv values.tmpl.yaml values.yaml
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/gateway-helm
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: verify templated variables
          work-dir: ${source.dir}/helm-charts/charts/gateway-helm
          runs: |
            set -eux -o pipefail

            if grep -E '\$\{[^}]+\}' values.yaml; then
              exit 1
            fi
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: gateway-helm
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: gateway-helm
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/envoy-gateway/config
