metadata:
  display-name: Temporal Helm Chart
  short-description: Temporal is a durable execution platform that enables developers to build scalable applications without sacrificing productivity or reliability.
  featured: false
  home-url: https://temporal.io/
  categories:
    - monitoring-and-observability
