# syntax=dhi.io/build:2-helm3

name: Istio ZTunnel Helm chart 1.x
image: dhi.io/ztunnel-chart
variant: helm
tags:
  - 1.27.8
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 4aee98e195c1af3f5e9385c637050db22d8c41d8
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  SEMVER_MAJOR_MINOR_VERSION: "1.27"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.27.8
  VERSION: 1.27.8
  ZTUNNEL_REFERENCE: dhi/ztunnel:1.27.8-debian13@sha256:c9c0cf70190542dd6993e0359f014c3776c4ce3868d8c40f8adc40d35503233b
contents:
  builds:
    - name: ztunnel
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.27.8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            chart:
              appRef: ztunnel
              description: Docker Hardened Images Helm chart for ZTunnel
              images:
                - name: ztunnel
                  ref: dhi/ztunnel:1.27.8-debian13@sha256:c9c0cf70190542dd6993e0359f014c3776c4ce3868d8c40f8adc40d35503233b
              name: ztunnel-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: ztunnel
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/ztunnel/config
