metadata:
  display-name: Prometheus Adapter Helm chart
  short-description: Helm chart for Prometheus Adapter (custom.metrics.k8s.io API) using Docker Hardened Images.
  featured: false
  home-url: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-adapter
  categories:
    - monitoring-and-observability
