metadata:
  display-name: Crossplane Helm chart
  short-description: Crossplane is an open source Kubernetes add-on that enables platform teams to assemble infrastructure from multiple vendors and expose higher level self-service APIs.
  featured: false
  home-url: https://www.crossplane.io/
  categories:
    - integration-and-delivery
