controller:
  image:
    repository: ${karpenter.registry}/${karpenter.repository}
    tag: ${karpenter.tag}
    digest: ${karpenter.digest}

podSecurityContext:
  fsGroup: 65532
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

settings:
  clusterName: "mycluster" # required placeholder, ideally should be set by user

serviceAccount:
  name: karpenter
