# syntax=dhi.io/build:2-alpine3.23

image: dhi.io/pkg-helm
variant: runtime
tags:
  - 3.20.1-alpine3.23
  - 3.20.1-r4-alpine3.23
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: a2369ca71c0ef633bf6e4fccd66d634eb379b371
  GOLANG_VERSION: 1.26.1-r3
  PACKAGE_NAME: helm
  REL: "4"
  SEMVER_MAJOR_MINOR_VERSION: "3.20"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.20.1
  VERSION: 3.20.1
contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
  packages:
    - alpine-baselayout-data
  builds:
    - name: helm
      work-dir: /go/src/github.com/helm/helm
      contents:
        packages:
          - busybox
          - bash
          - golang-1.26=1.26.1-r3
          - golang-1.26-oci-config=1.26.1-r3
          - sed
        files:
          - url: git+https://github.com/helm/helm.git#v3.20.1
            checksum: a2369ca71c0ef633bf6e4fccd66d634eb379b371
            path: /go/src/github.com/helm/helm
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          with:
            deps:
              - google.golang.org/grpc@v1.79.3
              - go.opentelemetry.io/contrib/exporters/autoexport@v0.67.0
            tidy: true
        - uses: go/hermetic@v1
        - name: build
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: false
            ldflags:
              - -X helm.sh/helm/v3/internal/version.version=3.20.1
              - -X helm.sh/helm/v3/internal/version.gitCommit=a2369ca71c0ef633bf6e4fccd66d634eb379b371
              - -X helm.sh/helm/v3/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v3/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm
            packages: ./cmd/helm
        - name: build dev
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: false
            ldflags:
              - -X helm.sh/helm/v3/internal/version.version=3.20.1
              - -X helm.sh/helm/v3/internal/version.gitCommit=a2369ca71c0ef633bf6e4fccd66d634eb379b371
              - -X helm.sh/helm/v3/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v3/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm-dev
            packages: ./cmd/helm
            strip: false
        - uses: sbom@v1
          with:
            prefix: helm-go
            source: ${target.dir}
        - uses: abuild/setup@v1
          work-dir: ${source.dir}/aports/helm
        - uses: abuild/apk@v1
          work-dir: ${source.dir}/aports/helm
          with:
            description: The Kubernetes Package Manager
            functions:
              dev: |
                pkgdesc="$pkgdesc (dev)"
                mkdir -p "$subpkgdir/usr/bin"
                mv "$pkgdir/usr/bin/helm-dev" "$subpkgdir/usr/bin/helm"
            license: Apache-2.0
            name: helm
            options: '!check !strip'
            rel: 4
            subpackages: $pkgname-dev
            url: https://github.com/helm/helm
            version: 3.20.1
        - uses: abuild/build@v1
          work-dir: ${source.dir}/aports/helm
os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.23"
  pretty-name: Docker Hardened Images/Alpine Linux v3.23
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
