server:
  image:
    repository: ${temporalio-server.registry}/${temporalio-server.repository}
    tag: ${temporalio-server.tag}@${temporalio-server.digest}
  securityContext:
    runAsNonRoot: true
    fsGroup: 65532
    runAsUser: 65532
  config:
    persistence:
      default:
        cassandra:
          port: 9602
      visibility:
        cassandra:
          port: 9602

admintools:
  image:
    repository: ${temporalio-admin-tools.registry}/${temporalio-admin-tools.repository}
    tag: ${temporalio-admin-tools.tag}@${temporalio-admin-tools.digest}
  securityContext:
    runAsNonRoot: true
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

web:
  image:
    repository: ${temporalio-ui.registry}/${temporalio-ui.repository}
    tag: ${temporalio-ui.tag}@${temporalio-ui.digest}
  securityContext:
    runAsNonRoot: true
    fsGroup: 5000
    runAsUser: 5000
    runAsGroup: 5000

schema:
  securityContext:
    runAsNonRoot: true
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

cassandra:
  enabled: false
elasticsearch:
  enabled: false
