image:
  repository: ${keycloak.registry}/${keycloak.repository}
  tag: ${keycloak.tag}
  digest: ${keycloak.digest}
podSecurityContext:
  fsGroup: 65532
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
# Command is set here explicitely to overwrite the --optimized flag that is configured
# in the image's command, in order to allow reconfiguration.
dbchecker:
  image:
    repository: ${busybox.registry}/${busybox.repository}
    tag: ${busybox.tag}@${busybox.digest}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
test:
  enabled: false
