image:
  registry: ${grafana-agent-operator.registry}
  repository: ${grafana-agent-operator.repository}
  tag: ${grafana-agent-operator.tag}@${grafana-agent-operator.digest}

test:
  grafana:
    image:
      registry: ${grafana-agent.registry}
      repository: ${grafana-agent.repository}
      tag: ${grafana-agent.tag}@${grafana-agent.digest}
  image:
    registry: ${busybox.registry}
    repository: ${busybox.repository}
    tag: ${busybox.tag}@${busybox.digest}

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

containerSecurityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
