# syntax=dhi.io/build:2-helm3

name: Redis Helm chart 23.x
image: dhi.io/redis-chart
variant: helm
tags:
  - 23.0.7
platforms:
  - linux/amd64
vars:
  BASH_REFERENCE: dhi/bash:5.2.37-debian13@sha256:b48311e0e7328043cc4a081626b44c4ea61190e9ab9c58cf703308f92f964296
  CHART_COMMIT_SHA: 4f7288e1b226ee2bfc150e507ffdca04a98a0952
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  KUBECTL_REFERENCE: dhi/kubectl:1.34.6-debian13-compat@sha256:3312d8ce5166d1061bcd04bb81098c8de605df365e69249902ebad43bfbc79da
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.82.0-debian13-compat@sha256:54e4547b38be00dd7a0a022a09591c54f0187102a70760be3c200adc24079330
  REDIS_REFERENCE: dhi/redis:8.2.5-debian13-compat@sha256:f84cc17994a8be294dc08282d228ab307e414c24741dfdff67a6e8402c6c14e0
  SEMVER_MAJOR_MINOR_VERSION: "23.0"
  SEMVER_MAJOR_VERSION: "23"
  SEMVER_VERSION: 23.0.7
  VERSION: 23.0.7
contents:
  builds:
    - name: redis
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#redis/23.0.7
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            chart:
              appRef: redis
              description: Docker Hardened Images Helm chart for Redis
              images:
                - name: redis
                  ref: dhi/redis:8.2.5-debian13-compat@sha256:f84cc17994a8be294dc08282d228ab307e414c24741dfdff67a6e8402c6c14e0
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.82.0-debian13-compat@sha256:54e4547b38be00dd7a0a022a09591c54f0187102a70760be3c200adc24079330
                - name: bash
                  ref: dhi/bash:5.2.37-debian13@sha256:b48311e0e7328043cc4a081626b44c4ea61190e9ab9c58cf703308f92f964296
                - name: kubectl
                  ref: dhi/kubectl:1.34.6-debian13-compat@sha256:3312d8ce5166d1061bcd04bb81098c8de605df365e69249902ebad43bfbc79da
              name: redis-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/redis
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: redis
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/redis
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/redis/config
