# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Cluster Helm chart 0.x
image: dhi.io/victoriametrics-cluster-chart
variant: helm
tags:
  - 0.38.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 205f2c0a8d19e7cb9e02d76a1efd5df696762d42
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  SEMVER_MAJOR_MINOR_VERSION: "0.38"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.38.0
  VERSION: 0.38.0
  VMAUTH_REFERENCE: dhi/victoriametrics-vmauth:1.139.0-debian13@sha256:dacd29b53f3a9fb4b77d8c2b95ed70f283147b37b390f5acd7be3ced1913f516
  VMINSERT_REFERENCE: dhi/victoriametrics-vminsert:1.139.0-debian13@sha256:3b07c0d2f809f3ffc256f4d9a2975d705fcae8b0bc9db8972a505f8f851a4062
  VMSELECT_REFERENCE: dhi/victoriametrics-vmselect:1.139.0-debian13@sha256:1e8f58e4ed7fe22c507354b2ba83cfe5da5fe5d3fe7451a7e860aae9e732b4bd
  VMSTORAGE_REFERENCE: dhi/victoriametrics-vmstorage:1.139.0-debian13@sha256:eb85e599e30366649019a4d3b49bf6ed32434fd685668892d3a1b8fd0a2d1bab
contents:
  builds:
    - name: victoriametrics-cluster-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-cluster-0.38.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            chart:
              appRef: victoriametrics-vmselect
              description: Docker Hardened Images Helm chart for VictoriaMetrics Cluster
              images:
                - name: victoriametrics-vmselect
                  ref: dhi/victoriametrics-vmselect:1.139.0-debian13@sha256:1e8f58e4ed7fe22c507354b2ba83cfe5da5fe5d3fe7451a7e860aae9e732b4bd
                - name: victoriametrics-vmstorage
                  ref: dhi/victoriametrics-vmstorage:1.139.0-debian13@sha256:eb85e599e30366649019a4d3b49bf6ed32434fd685668892d3a1b8fd0a2d1bab
                - name: victoriametrics-vminsert
                  ref: dhi/victoriametrics-vminsert:1.139.0-debian13@sha256:3b07c0d2f809f3ffc256f4d9a2975d705fcae8b0bc9db8972a505f8f851a4062
                - name: victoriametrics-vmauth
                  ref: dhi/victoriametrics-vmauth:1.139.0-debian13@sha256:dacd29b53f3a9fb4b77d8c2b95ed70f283147b37b390f5acd7be3ced1913f516
              name: victoriametrics-cluster-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update sidecar values
          uses: yq/patch@v1
          with:
            file: ${source.dir}/helm-charts/charts/victoria-metrics-cluster/values-sidecar.yaml
            patches:
              - .extraContainers[0].image = "dhi/victoriametrics-vmauth:1.139.0-debian13@sha256:dacd29b53f3a9fb4b77d8c2b95ed70f283147b37b390f5acd7be3ced1913f516"
              - .extraContainers[0].securityContext.enabled = true
              - .extraContainers[0].securityContext.runAsNonRoot = true
              - .extraContainers[0].securityContext.runAsUser = 65532
              - .extraContainers[0].securityContext.runAsGroup = 65532
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for victoriametrics/vmbackupmanager
            sed -i '/- name: vmbackupmanager/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/vmstorage-server.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-cluster
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-cluster/config
