image:
  repository: ${prometheus-adapter.registry}/${prometheus-adapter.repository}
  tag: ${prometheus-adapter.tag}@${prometheus-adapter.digest}

# Override upstream 10001 to use DHI non-root user 65532
podSecurityContext:
  fsGroup: 65532

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
