image:
  repository: ${crossplane.registry}/${crossplane.repository}
  tag: ${crossplane.tag}@${crossplane.digest}

imagePullSecrets: []

securityContextCrossplane:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

securityContextRBACManager:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

podSecurityContextCrossplane:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true

podSecurityContextRBACManager:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
