metadata:
  display-name: Grafana k6-operator Helm chart
  short-description: Helm chart for the Grafana k6 Kubernetes operator
  featured: false
  home-url: https://github.com/grafana/k6-operator
  categories:
    - developer-tools
