deployment:
  image:
    repository: ${apisix-ingress-controller.registry}/${apisix-ingress-controller.repository}
    tag: ${apisix-ingress-controller.tag}@${apisix-ingress-controller.digest}

  adcContainer:
    image:
      repository: ${adc.registry}/${adc.repository}
      tag: ${adc.tag}@${adc.digest}

  podSecurityContext:
    runAsNonRoot: true
    runAsGroup: 65532
    runAsUser: 65532

  securityContext:
    runAsNonRoot: true
    runAsGroup: 65532
    runAsUser: 65532

imagePullSecrets: []
