metadata:
  display-name: Karpenter
  short-description: Open-source Kubernetes node autoscaler built for flexibility, performance, and simplicity
  featured: false
  home-url: https://karpenter.sh/
  categories:
    - integration-and-delivery
