image:
  repository: ${apisix.registry}/${apisix.repository}
  tag: ${apisix.tag}@${apisix.digest}

securityContext:
  runAsNonRoot: true
  runAsGroup: 65532
  runAsUser: 65532

podSecurityContext:
  runAsNonRoot: true
  runAsGroup: 65532
  runAsUser: 65532

initContainer:
  image: ${busybox.registry}/${busybox.repository}
  tag: ${busybox.tag}@${busybox.digest}

etcd:
  enabled: false
  auth:
    tls:
      enabled: false
