# syntax=dhi.io/build:2-debian13

name: Docker 29.x (cli, dev)
image: dhi.io/docker
variant: dev
flavor: cli
tags:
  - 29-cli-dev
  - 29.3-cli-dev
  - 29.3.1-cli-dev
  - 29-debian13-cli-dev
  - 29.3-debian13-cli-dev
  - 29.3.1-debian13-cli-dev
platforms:
  - linux/amd64
  - linux/arm64
vars:
  BUILDX_COMMIT_SHA: f7897eba028583e0071642db3c011e860444f8cf
  BUILDX_VERSION: 0.33.0
  COMMIT_SHA: c2be9ccfc3cf0b4c4c4f0a3d5c91dd759ab21256
  COMPOSE_COMMIT_SHA: b043368028e9fcb4545fa340c8ad635c370825da
  COMPOSE_VERSION: 5.1.1
  GOLANG_REFERENCE: dhi/golang:1.25.8-debian13-dev@sha256:b2c03c829a4df4f724712501d18321e46a2ac770377f0b6e2f383bc9d02b99d3
  SCOUT_CLI_PLUGIN_COMMIT_SHA: 3d7473c3cd29fc1c10c7915445efd2f9f00929f5
  SCOUT_CLI_PLUGIN_VERSION: 1.20.3
  SEMVER_MAJOR_MINOR_VERSION: "29.3"
  SEMVER_MAJOR_VERSION: "29"
  SEMVER_VERSION: 29.3.1
  VERSION: 29.3.1
contents:
  packages:
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - base-files
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - grep
    - libc-bin
    - libc6
    - mawk
    - perl-base
    - sed
    - util-linux
  builds:
    - name: buildx
      uses: dhi.io/golang:1.25.8-debian13-dev@sha256:b2c03c829a4df4f724712501d18321e46a2ac770377f0b6e2f383bc9d02b99d3
      work-dir: /go/src/github.com/docker/buildx
      caches:
        - path: /go/pkg/mod
      contents:
        packages:
          - gnu-which
        files:
          - url: git+https://github.com/docker/buildx.git#v0.33.0
            checksum: f7897eba028583e0071642db3c011e860444f8cf
            path: /go/src/github.com/docker/buildx
            spdx:
              name: docker-buildx
              version: 0.33.0
              packages:
                - name: buildx
                  purl: pkg:golang/github.com/docker/buildx@0.33.0
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          work-dir: /go/src/github.com/docker/buildx
          privileged: true
          environment:
            GODEBUG: ""
            GOFIPS140: ""
          runs: |
            set -eux -o pipefail

            go get github.com/sigstore/rekor@v1.5.0               # CVE-2026-24117, CVE-2026-23831
            go get github.com/theupdateframework/go-tuf/v2@v2.4.1 # CVE-2026-24686
            go get go.opentelemetry.io/otel/sdk@v1.40.0           # CVE-2026-24051
            go get github.com/cloudflare/circl@v1.6.3             # CVE-2026-1229
            go get google.golang.org/grpc@v1.79.3                 # CVE-2026-33186
            go mod tidy
            go mod vendor
        - name: go build
          uses: go/build@v1
          with:
            ldflags:
              - -X github.com/docker/buildx/version.Version=0.33.0
              - -X github.com/docker/buildx/version.Revision=f7897eba028583e0071642db3c011e860444f8cf
              - -X github.com/docker/buildx/version.Package=github.com/docker/buildx
            output: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-buildx
            packages: ./cmd/buildx
      outputs:
        - source: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-buildx
          target: /usr/local/libexec/docker/cli-plugins/docker-buildx
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/docker-buildx
          target: /opt/docker/sbom/docker-buildx
          uid: 0
          gid: 0
    - name: compose
      uses: dhi.io/golang:1.25.8-debian13-dev@sha256:b2c03c829a4df4f724712501d18321e46a2ac770377f0b6e2f383bc9d02b99d3
      work-dir: /go/src/github.com/docker/compose
      contents:
        packages:
          - bash
          - btrfs-progs
          - build-essential
          - ca-certificates
          - libseccomp-dev
          - libtool
          - linux-libc-dev
          - liblvm2-dev
        files:
          - url: git+https://github.com/docker/compose.git#v5.1.1
            checksum: b043368028e9fcb4545fa340c8ad635c370825da
            path: /go/src/github.com/docker/compose
            spdx:
              name: docker-compose
              version: 5.1.1
              packages:
                - name: compose
                  purl: pkg:golang/github.com/docker/compose@5.1.1
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: go dependencies
          uses: go/bump@v1
          with:
            deps:
              - go.opentelemetry.io/otel/sdk@v1.40.0
              - github.com/sigstore/sigstore@v1.10.4
              - google.golang.org/grpc@v1.79.3
            tidy: true
        - uses: go/hermetic@v1
        - name: build
          privileged: true
          runs: |
            set -eux -o pipefail

            mkdir -p "${target.dir}/usr/local/libexec/docker/cli-plugins"
            GODEBUG="fips140=on" DESTDIR="${target.dir}/usr/local/libexec/docker/cli-plugins" make build
      outputs:
        - source: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-compose
          target: /usr/local/libexec/docker/cli-plugins/docker-compose
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/docker-compose
          target: /opt/docker/sbom/docker-compose
          uid: 0
          gid: 0
    - name: scout
      uses: dhi.io/golang:1.25.8-debian13-dev@sha256:b2c03c829a4df4f724712501d18321e46a2ac770377f0b6e2f383bc9d02b99d3
      work-dir: /go/src/github.com/docker/scout-cli-plugin
      contents:
        files:
          - url: git+https://github.com/docker/scout-cli-plugin.git#v1.20.3
            checksum: 3d7473c3cd29fc1c10c7915445efd2f9f00929f5
            path: /go/src/github.com/docker/scout-cli-plugin
            spdx:
              name: scout-cli
              version: 1.20.3
              packages:
                - name: scout-cli
                  purl: pkg:github/docker/scout-cli-plugin@1.20.3
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: go dependencies
          uses: go/bump@v1
          with:
            deps:
              - github.com/theupdateframework/go-tuf/v2@v2.4.1
              - github.com/sigstore/rekor@v1.5.0
              - github.com/sigstore/sigstore@v1.10.4
              - github.com/cloudflare/circl@v1.6.3
              - go.opentelemetry.io/otel/sdk@v1.40.0
              - google.golang.org/grpc@v1.79.3
            replaces:
              - github.com/sigstore/sigstore=github.com/sigstore/sigstore@v1.10.4
            tidy: true
        - uses: go/hermetic@v1
        - name: build
          uses: go/build@v1
          with:
            ldflags:
              - -X github.com/docker/scout-cli-plugin/internal/version.version=1.20.3
              - -X github.com/docker/scout-cli-plugin/internal/version.commit=3d7473c3cd29fc1c10c7915445efd2f9f00929f5
            output: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-scout
            packages: ./cmd/docker-scout
      outputs:
        - source: ${target.dir}/usr/local/libexec/docker/cli-plugins/docker-scout
          target: /usr/local/libexec/docker/cli-plugins/docker-scout
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/scout-cli
          target: /opt/docker/sbom/scout-cli
          uid: 0
          gid: 0
    - name: docker-cli
      uses: dhi.io/golang:1.25.8-debian13-dev@sha256:b2c03c829a4df4f724712501d18321e46a2ac770377f0b6e2f383bc9d02b99d3
      contents:
        packages:
          - bash
          - btrfs-progs
          - build-essential
          - ca-certificates
          - libseccomp-dev
          - libtool
          - linux-libc-dev
          - liblvm2-dev
        files:
          - url: git+https://github.com/docker/cli.git#v29.3.1
            checksum: c2be9ccfc3cf0b4c4c4f0a3d5c91dd759ab21256
            path: /go/src/github.com/docker/cli
            spdx:
              name: docker-cli
              version: 29.3.1
              packages:
                - name: docker-cli
                  purl: pkg:golang/github.com/docker/cli@29.3.1
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: build
          work-dir: /go/src/github.com/docker/cli
          runs: |
            set -eux -o pipefail

            export DISABLE_WARN_OUTSIDE_CONTAINER=1
            export LDFLAGS=""
            export CGO_ENABLED=1

            make VERSION="29.3.1" dynbinary

            install -Dm755 build/docker-linux-* "${target.dir}/usr/local/bin/docker"
      outputs:
        - source: ${target.dir}/usr/local/bin/docker
          target: /usr/local/bin/docker
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/docker-cli
          target: /opt/docker/sbom/docker-cli
          uid: 0
          gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: docker
      gid: 2375
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
environment:
  DEBIAN_FRONTEND: noninteractive
  DOCKER_BUILDX_VERSION: 0.33.0
  DOCKER_COMPOSE_VERSION: 5.1.1
  DOCKER_TLS_CERTDIR: /cert
  DOCKER_VERSION: 29.3.1
paths:
  - type: directory
    path: /certs/client
    uid: 0
    gid: 0
annotations:
  org.opencontainers.image.description: A minimal Docker image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - docker
