# syntax=dhi.io/build:2-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.32.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 3e032ad7685f80fc2a021e282a52b6d2fbd37a07
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  SEMVER_MAJOR_MINOR_VERSION: "0.32"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.32.0
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.1-debian13@sha256:a2302791e0c2517c945c9fb377eb73a3663b3aa4619d27abe487fb2ee08b6ab2
  VAULT_HELM_REFERENCE: dhi/vault:1.21.4-debian13-helm@sha256:13ee377b59a0ea13506cd22c3243759615421b10d114ad2c4935cb8b960d2a4c
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.3-debian13@sha256:4b4258e88d2755f16d85bddcae810253d3388c0f054c806d370299089a11244a
  VAULT_REFERENCE: dhi/vault:1.21.4-debian13@sha256:c0e121fb9ed7a42bb3798118fd37f8c656f438e7a395a1fda32c8540aa619306
  VERSION: 0.32.0
contents:
  builds:
    - name: vault
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.32.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.4-debian13@sha256:c0e121fb9ed7a42bb3798118fd37f8c656f438e7a395a1fda32c8540aa619306
                - name: vault-helm
                  ref: dhi/vault:1.21.4-debian13-helm@sha256:13ee377b59a0ea13506cd22c3243759615421b10d114ad2c4935cb8b960d2a4c
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.3-debian13@sha256:4b4258e88d2755f16d85bddcae810253d3388c0f054c806d370299089a11244a
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.1-debian13@sha256:a2302791e0c2517c945c9fb377eb73a3663b3aa4619d27abe487fb2ee08b6ab2
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
