# syntax=dhi.io/build:2-helm3

name: Istio Discovery (istiod) Helm chart 1.x
image: dhi.io/istio-discovery-chart
variant: helm
tags:
  - 1.28.5
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 7da6662175184479cb9281f3d814d6994bf1009f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  ISTIO_PILOT_REFERENCE: dhi/istio-pilot:1.28.5-debian13@sha256:31d3423259cbc61f90391752e07220c1dfe4646a9df54a5371202ba65ffaeaac
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.28.5-debian13@sha256:02b511804cacd597e1d0315db58bec68a5a8784fceaa15f9c4242ea8d1937cc3
  SEMVER_MAJOR_MINOR_VERSION: "1.28"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.28.5
  VERSION: 1.28.5
contents:
  builds:
    - name: istio-discovery
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      work-dir: /src/go/github.com/istio/istio/manifests/charts/istio-control/istio-discovery
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.28.5
            path: /src/go/github.com/istio/istio
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: pilot
              description: Docker Hardened Images Helm chart for Istio Discovery (istiod)
              images:
                - name: pilot
                  ref: dhi/istio-pilot:1.28.5-debian13@sha256:31d3423259cbc61f90391752e07220c1dfe4646a9df54a5371202ba65ffaeaac
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.28.5-debian13@sha256:02b511804cacd597e1d0315db58bec68a5a8784fceaa15f9c4242ea8d1937cc3
              name: istio-discovery-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-discovery/config
