global:
  images:
    envoyGateway:
      image: ${envoy-gateway.registry}/${envoy-gateway.repository}:${envoy-gateway.tag}@${envoy-gateway.digest}
      pullPolicy: IfNotPresent
    ratelimit:
      image: ${envoy-ratelimit.registry}/${envoy-ratelimit.repository}:${envoy-ratelimit.tag}@${envoy-ratelimit.digest}
      pullPolicy: IfNotPresent

deployment:
  envoyGateway:
    securityContext:
      runAsNonRoot: true
      runAsGroup: 65532
      runAsUser: 65532
certgen:
  job:
    securityContext:
      runAsNonRoot: true
      runAsGroup: 65532
      runAsUser: 65532

config:
  envoyGateway:
    envoyProxy:
      provider:
        type: Kubernetes
        kubernetes:
          envoyDeployment:
            container:
              image: ${envoy.registry}/${envoy.repository}:${envoy.tag}@${envoy.digest}
              securityContext:
                runAsNonRoot: true
                runAsGroup: 65532
                runAsUser: 65532
            pod:
              imagePullSecrets: []
# The upstream chart already specifies this security context, repeat it here in case it would change
