metadata:
  display-name: APISIX Ingress Controller Helm chart
  short-description: The APISIX Ingress Controller Helm chart is an open source project for running the APISIX Gateway as a Kubernetes Ingress.
  featured: false
  home-url: https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix-ingress-controller
  categories:
    - networking
