# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 0.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 0.74.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:11.3.7@sha256:bc6ccb83070efcb622919c80529932b0dc6c185295204250abde5da68b077ffa
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  PROMETHEUS_CHART_REFERENCE: dhi/prometheus-chart:28.15.0@sha256:c44eab5ed754876b2e643f59abe3e2960ed00b16f4a40b4e35362c21c2b24e96
  SEMVER_MAJOR_MINOR_VERSION: "0.74"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.74.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.28.3-cli-1.6.2-debian13@sha256:d462b5711aa26b8bc7a27d8fc90ea13e19fe03510cd96d398f2d87988a09630b
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.28.3-cli-1.6.2-debian13@sha256:d0b622b4440792354641727e546621f4a8eae0471a78dc927fb3519a306d4fb7
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.48.1-debian13@sha256:995974ef9c22c08cf7b7401bc0470f8d48a33a5893756b423998a3f71c610dba
  VERSION: 0.74.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-0.74.0
            checksum: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              dependencies:
                - alias: prometheus
                  condition: prometheus.enabled
                  name: prometheus
                  ref: dhi/prometheus-chart:28.15.0@sha256:c44eab5ed754876b2e643f59abe3e2960ed00b16f4a40b4e35362c21c2b24e96
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:11.3.7@sha256:bc6ccb83070efcb622919c80529932b0dc6c185295204250abde5da68b077ffa
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.28.3-cli-1.6.2-debian13@sha256:d0b622b4440792354641727e546621f4a8eae0471a78dc927fb3519a306d4fb7
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.28.3-cli-1.6.2-debian13@sha256:d462b5711aa26b8bc7a27d8fc90ea13e19fe03510cd96d398f2d87988a09630b
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.48.1-debian13@sha256:995974ef9c22c08cf7b7401bc0470f8d48a33a5893756b423998a3f71c610dba
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          with:
            file: values.yaml
            patches:
              - del(.cassandra)
              - del(.elasticsearch)
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: temporal
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config
