manager:
  image:
    registry: ${k6-operator.registry}
    repository: ${k6-operator.repository}
    tag: ${k6-operator.tag}@${k6-operator.digest}
  podSecurityContext:
    fsGroup: 65532
  containerSecurityContext:
    runAsUser: 65532
    runAsNonRoot: true
    runAsGroup: 65532
